development:
  adapter: postgresql
  database: chef-made-development
  template: template0
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database:  chef-made-test
  template: template0
  pool: 5
  timeout: 5000

production:
  # adapter: postgresql
  # database:  chef-made-production
  # template: template0
  # pool: 5
  # timeout: 5000
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: capacitor
  password: capacitor
  database: chef-made-production
  host: localhost
  port: 5432
